### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by banbsyip** [liuheng92/tensorflow_PSENet#45]
WARNING: Logging before flag parsing goes to stderr.
I0918 17:56:17.906025 18412 pyplot.py:219] Loaded backend qt5agg version unknown.
I0918 17:56:17.948019 18412 pyplot.py:219] Loaded backend qt5agg version unknown.
I0918 17:56:17.948019 18412 pyplot.py:219] Loaded backend Qt5Agg version unknown.
Traceback (most recent call last):
C:\Users\sas\Desktop\tensorflow_PSENet-master\pse
  File "C:/Users/sas/Desktop/tensorflow_PSENet-master/eval.py", line 20, in <module>
    from pse import pse
  File "C:\Users\sas\Desktop\tensorflow_PSENet-master\pse\__init__.py", line 9, in <module>
    if subprocess.call(['make', '-C', BASE_DIR]) != 0:  # return value
  File "C:\software\Anaconda\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\software\Anaconda\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\software\Anaconda\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
请问作者这块问题如何解决呢？是不是编译c++文件出错？

**Comment by banbsyip** [comment]
编译问题，需要在Linux下进行编译
